using System.Collections.Generic;

namespace BusinessesDirectoryApi.Helpers
{
  public static class UnsafeWordsChecker
  {
    private static List<string> unsafeWords = new List<string>{
      "BICHO",
      "BICH0",
      "B1CHO",
      "B1CH0",
      "VICHO",
      "V1CHO",
      "VICH0",
      "V1CH0",
      "CHOCHO",
      "CH0CH0",
      "C#0C#0",
      "VERGA",
      "V3RGA",
      "V3RG4",
      "ORTO",
      "0RT0",
      "ORT0",
      "ORT0",
      "anal",
      "anus",
      "arse",
      "ass",
      "ballsack",
      "balls",
      "bastard",
      "bitch",
      "biatch",
      "bloody",
      "blowjob",
      "blow job",
      "bollock",
      "bollok",
      "boner",
      "boob",
      "bugger",
      "bum",
      "butt",
      "buttplug",
      "clitoris",
      "cock",
      "coon",
      "crap",
      "cunt",
      "damn",
      "dick",
      "dildo",
      "dyke",
      "fag",
      "feck",
      "fellate",
      "fellatio",
      "felching",
      "fuck",
      "f u c k",
      "fudgepacker",
      "fudge packer",
      "flange",
      "Goddamn",
      "God damn",
      "hell",
      "homo",
      "jerk",
      "jizz",
      "knobend",
      "knob end",
      "labia",
      "lmao",
      "lmfao",
      "muff",
      "nigger",
      "nigga",
      "omg",
      "penis",
      "piss",
      "poop",
      "prick",
      "pube",
      "pussy",
      "queer",
      "scrotum",
      "sex",
      "shit",
      "s hit",
      "sh1t",
      "slut",
      "smegma",
      "spunk",
      "tit",
      "tosser",
      "turd",
      "twat",
      "vagina",
      "wank",
      "whore",
      "wtf",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    };
    public static bool IsSafe(this string obj)
    {
      foreach(var word in unsafeWords)
      {
        if (obj.ToUpper().Contains(word))
        {
          return false;
        }
      }
      return true;
    }
  }
}
